import {
 Users,
 BookOpen,
 Clock,
 DollarSign,
 TrendingUp,
 Target,
 CheckCircle,
 AlertCircle,
 Calendar,
 Brain,
 ArrowRight,
 Activity,
 Mail,
 Phone,
 MapPin,
 ArrowLeft,
 Edit,
 Download,
 FileText,
 Plus,
 Search,
 Filter,
 Settings,
 LogOut,
 Menu,
 X,
 ChevronRight,
 Bell,
 Lock,
 RefreshCw,
 LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
 users: Users,
 bookOpen: BookOpen,
 clock: Clock,
 dollarSign: DollarSign,
 trendingUp: TrendingUp,
 target: Target,
 checkCircle: CheckCircle,
 alertCircle: AlertCircle,
 calendar: Calendar,
 brain: Brain,
 arrowRight: ArrowRight,
 activity: Activity,
 mail: Mail,
 phone: Phone,
 mapPin: MapPin,
 arrowLeft: ArrowLeft,
 edit: Edit,
 download: Download,
 fileText: FileText,
 plus: Plus,
 search: Search,
 filter: Filter,
 settings: Settings,
 logOut: LogOut,
 menu: Menu,
 x: X,
 chevronRight: ChevronRight,
 bell: Bell,
 lock: Lock,
 refreshCw: RefreshCw,
};

export type IconKey = keyof typeof ICON_MAP;

export function getIcon(key: IconKey): LucideIcon {
 return ICON_MAP[key] || Users;
}
