
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.10.0
 * Query Engine version: 0edf323efd1d98336f3f0a68684b56f689b900d3
 */
Prisma.prismaVersion = {
  client: "7.10.0",
  engine: "0edf323efd1d98336f3f0a68684b56f689b900d3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  course: 'course',
  subject: 'subject',
  teacher: 'teacher',
  classroom: 'classroom',
  maxStudents: 'maxStudents',
  startDate: 'startDate',
  endDate: 'endDate',
  price: 'price',
  monthlyFee: 'monthlyFee',
  description: 'description',
  status: 'status',
  schedule: 'schedule',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudentProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  groupId: 'groupId',
  enrollmentDate: 'enrollmentDate',
  status: 'status',
  monthlyFee: 'monthlyFee',
  paid: 'paid',
  debt: 'debt',
  referralCode: 'referralCode',
  referredByUserId: 'referredByUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MonthlyResultScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  month: 'month',
  mathScore: 'mathScore',
  englishScore: 'englishScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  groupId: 'groupId',
  date: 'date',
  status: 'status',
  note: 'note',
  recordedBy: 'recordedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  groupId: 'groupId',
  amountPaid: 'amountPaid',
  month: 'month',
  status: 'status',
  notes: 'notes',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudentNoteScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TopicScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subject: 'subject',
  description: 'description',
  bookTitle: 'bookTitle',
  bookPdfPath: 'bookPdfPath',
  videoPath: 'videoPath',
  orderIndex: 'orderIndex',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GroupTopicProgressScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  topicId: 'topicId',
  isApproved: 'isApproved',
  approvedAt: 'approvedAt',
  order: 'order'
};

exports.Prisma.MockTestScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  subject: 'subject',
  testName: 'testName',
  description: 'description',
  maxScore: 'maxScore',
  duration: 'duration',
  score: 'score',
  answers: 'answers',
  questions: 'questions',
  notes: 'notes',
  source: 'source',
  createdById: 'createdById',
  status: 'status',
  approvedAt: 'approvedAt',
  approvedBy: 'approvedBy',
  isLockedInMetrics: 'isLockedInMetrics',
  uploadedFileName: 'uploadedFileName',
  uploadedAt: 'uploadedAt',
  mathScore: 'mathScore',
  englishScore: 'englishScore',
  totalScore: 'totalScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TopicPerformanceScalarFieldEnum = {
  id: 'id',
  mockTestId: 'mockTestId',
  topicId: 'topicId',
  percentage: 'percentage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockTestAttachmentScalarFieldEnum = {
  id: 'id',
  mockTestId: 'mockTestId',
  fileName: 'fileName',
  fileType: 'fileType',
  fileSize: 'fileSize',
  storageKey: 'storageKey',
  uploadedAt: 'uploadedAt'
};

exports.Prisma.ParentGuardianScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  fullName: 'fullName',
  phone: 'phone',
  smsNotifyEnabled: 'smsNotifyEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SmsNotificationScalarFieldEnum = {
  id: 'id',
  parentGuardianId: 'parentGuardianId',
  studentId: 'studentId',
  mockTestId: 'mockTestId',
  message: 'message',
  status: 'status',
  provider: 'provider',
  providerMessageId: 'providerMessageId',
  errorMessage: 'errorMessage',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
};

exports.Prisma.SATMockTestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdById: 'createdById',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SATQuestionScalarFieldEnum = {
  id: 'id',
  satTestId: 'satTestId',
  module: 'module',
  format: 'format',
  questionNumber: 'questionNumber',
  prompt: 'prompt',
  passage: 'passage',
  imageUrl: 'imageUrl',
  imagePosition: 'imagePosition',
  options: 'options',
  correctAnswer: 'correctAnswer',
  answerSource: 'answerSource',
  requiresReview: 'requiresReview',
  verificationStatus: 'verificationStatus',
  difficulty: 'difficulty',
  domain: 'domain',
  skill: 'skill',
  explanation: 'explanation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudentTestAttemptScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  satTestId: 'satTestId',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  totalTimeMs: 'totalTimeMs',
  totalScore: 'totalScore',
  rwScore: 'rwScore',
  mathScore: 'mathScore',
  rwRaw: 'rwRaw',
  mathRaw: 'mathRaw',
  rwTotal: 'rwTotal',
  mathTotal: 'mathTotal',
  userAnswers: 'userAnswers',
  markedQuestions: 'markedQuestions',
  proctorCode: 'proctorCode',
  scoringStatus: 'scoringStatus',
  aiEstimatedScore: 'aiEstimatedScore',
  fullscreenExitCount: 'fullscreenExitCount',
  reviewIndex: 'reviewIndex',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProctoredSessionScalarFieldEnum = {
  id: 'id',
  code: 'code',
  satTestId: 'satTestId',
  createdById: 'createdById',
  status: 'status',
  scoringStatus: 'scoringStatus',
  scoringStartedAt: 'scoringStartedAt',
  scoredAt: 'scoredAt',
  publishedAt: 'publishedAt',
  publishAfter: 'publishAfter',
  scoredCount: 'scoredCount',
  totalParticipants: 'totalParticipants',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProctoredParticipantScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  studentId: 'studentId',
  userName: 'userName',
  email: 'email',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  currentModule: 'currentModule',
  fullscreenExitCount: 'fullscreenExitCount',
  score: 'score',
  currentQuestionIndex: 'currentQuestionIndex',
  timeRemaining: 'timeRemaining',
  lastHeartbeat: 'lastHeartbeat',
  timeAdded: 'timeAdded',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BugReportScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  satTestId: 'satTestId',
  questionId: 'questionId',
  issueType: 'issueType',
  message: 'message',
  screenshot: 'screenshot',
  status: 'status',
  priority: 'priority',
  aiAnalysis: 'aiAnalysis',
  suggestedFix: 'suggestedFix',
  fixPayload: 'fixPayload',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReferralScalarFieldEnum = {
  id: 'id',
  referrerId: 'referrerId',
  referredStudentId: 'referredStudentId',
  completedAt: 'completedAt',
  satTestId: 'satTestId',
  testAttemptId: 'testAttemptId',
  createdAt: 'createdAt'
};

exports.Prisma.StudyGroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdById: 'createdById',
  memberIds: 'memberIds',
  testIds: 'testIds',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ArticleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  category: 'category',
  summary: 'summary',
  content: 'content',
  coverImage: 'coverImage',
  readTimeMin: 'readTimeMin',
  published: 'published',
  viewsCount: 'viewsCount',
  vocabulary: 'vocabulary',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIJobScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  userId: 'userId',
  sourceFileId: 'sourceFileId',
  progress: 'progress',
  currentStep: 'currentStep',
  attempts: 'attempts',
  maxAttempts: 'maxAttempts',
  errorCode: 'errorCode',
  errorMessage: 'errorMessage',
  inputData: 'inputData',
  resultData: 'resultData',
  provider: 'provider',
  model: 'model',
  createdAt: 'createdAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT'
};

exports.StudentStatus = exports.$Enums.StudentStatus = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  INACTIVE: 'INACTIVE'
};

exports.AttendanceStatus = exports.$Enums.AttendanceStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED'
};

exports.MockTestSource = exports.$Enums.MockTestSource = {
  STUDENT_UPLOADED: 'STUDENT_UPLOADED',
  ADMIN_ENTERED: 'ADMIN_ENTERED'
};

exports.MockTestStatus = exports.$Enums.MockTestStatus = {
  PENDING: 'PENDING',
  AI_PROPOSED: 'AI_PROPOSED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED'
};

exports.SmsStatus = exports.$Enums.SmsStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
};

exports.MockTestModule = exports.$Enums.MockTestModule = {
  MODULE_1: 'MODULE_1',
  MODULE_2: 'MODULE_2',
  MODULE_3: 'MODULE_3',
  MODULE_4: 'MODULE_4'
};

exports.MockTestFormat = exports.$Enums.MockTestFormat = {
  MCQ: 'MCQ',
  FILL_IN: 'FILL_IN'
};

exports.QuestionDifficulty = exports.$Enums.QuestionDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
};

exports.ScoringStatus = exports.$Enums.ScoringStatus = {
  PUBLISHED: 'PUBLISHED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  SCORED: 'SCORED'
};

exports.ProctoredSessionStatus = exports.$Enums.ProctoredSessionStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  REVOKED: 'REVOKED'
};

exports.ParticipantStatus = exports.$Enums.ParticipantStatus = {
  WAITING: 'WAITING',
  TAKING: 'TAKING',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  DISQUALIFIED: 'DISQUALIFIED'
};

exports.AIJobType = exports.$Enums.AIJobType = {
  MOCK_TEST_IMPORT: 'MOCK_TEST_IMPORT',
  ARTICLE_IMPORT: 'ARTICLE_IMPORT',
  BLUEBOOK_ANALYSIS: 'BLUEBOOK_ANALYSIS',
  STUDENT_ANALYSIS: 'STUDENT_ANALYSIS'
};

exports.AIJobStatus = exports.$Enums.AIJobStatus = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  VALIDATING: 'VALIDATING',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Group: 'Group',
  StudentProfile: 'StudentProfile',
  MonthlyResult: 'MonthlyResult',
  Attendance: 'Attendance',
  Payment: 'Payment',
  StudentNote: 'StudentNote',
  Topic: 'Topic',
  GroupTopicProgress: 'GroupTopicProgress',
  MockTest: 'MockTest',
  TopicPerformance: 'TopicPerformance',
  MockTestAttachment: 'MockTestAttachment',
  ParentGuardian: 'ParentGuardian',
  SmsNotification: 'SmsNotification',
  SATMockTest: 'SATMockTest',
  SATQuestion: 'SATQuestion',
  StudentTestAttempt: 'StudentTestAttempt',
  ProctoredSession: 'ProctoredSession',
  ProctoredParticipant: 'ProctoredParticipant',
  BugReport: 'BugReport',
  Referral: 'Referral',
  StudyGroup: 'StudyGroup',
  Article: 'Article',
  AIJob: 'AIJob'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
